name: Docker Build and scan
on:
  push
env:
  DOCKER_VER_TAG: 1.14.2-rc.0
  
jobs:
  docker_build:
    name: "Build docker deploy to docker hub"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build, tag, and push image to Docker hub
        id: build-image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t v3dotcash/elixir-redhat-builder:$DOCKER_VER_TAG .
          docker push v3dotcash/elixir-redhat-builder:$DOCKER_VER_TAG
          echo "::set-output name=v3dotcash/elixir-redhat-builder:$DOCKER_VER_TAG"
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
            image-ref: "v3dotcash/elixir-redhat-builder:${{env.DOCKER_VER_TAG}}"
            format: 'table'
            exit-code: '1'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'
            scanners: vuln
